### ISSUE TITLE
Update du MontantTotal après clic sur Participer

### ISSUE THREAD

**Issue by Binnette** [barmic/cotize#1]
Comment reproduire :
1. Ouvrir un projet existant
2. Regarder le montant total (ex: 40€)
3. Ajouter une participation de 20 €
4. Cliquer sur Participer
5. Attendre le rechargement de la page
:boom: La page affiche toujours 40€ au lieu d'afficher 60€ :sob:

**Comment by barmic** [comment]
Plus d'actualité
