### ISSUE TITLE
Le lien pour modifier ma cotisation n’apparaît pas

### ISSUE THREAD

**Issue by Binnette** [barmic/cotize#2]
Après l'ajout de ma contribution, il est affiché
> Vous pouvez éditer celle-ci avec le lien suivant !

:boom: Or aucun lien n'est affiché. Cf screenshot

![image](https://cloud.githubusercontent.com/assets/6597721/9492759/c83a8c52-4bfa-11e5-8cc3-6a00abdba995.png)

**Comment by barmic** [comment]
Plus d'actualité
