### ISSUE TITLE
Message d'erreur pas assez clairs

### ISSUE THREAD

**Issue by barmic** [barmic/cotize#6]
Les messages d'erreur ne sont pas assez clair. Exemple :

"ne peut pas être vide"

**Comment by RachelDSS** [comment]
- Lorsque qu'un champ est obligatoire il faut indiquer quel champ "ne peux pas etre vide"
- A la page de création d'un projet si on clique sur créer directement sans rien saisir on a juste "Erreur"
- Dans la page de participation si je ne mets pas de 
       * **montant ** j'ai : "java.lang.String cannot be cast to java.lang.Number"
       * **nom ou de mail ** j'ai : "ne peut pas être vide ne peut pas être nul" (les deux messages pour une seule erreur)
